remote_theme: jekyll/minima@d4d779a

title: Carson Mann CS 499 ePortfolio

author:
  name: Carson Mann
  
description: SNHU Computer Science Program Portfolio
url: "https://poundofcheese.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

hide_site_feed_link: true
